# Generated by Django 3.0.5 on 2020-12-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='album/image')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='album/images')),
                ('album', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.Album')),
            ],
        ),
    ]
